// commands/launch.ts — `smalltalk launch <claude|codex>` verb.
//
// One-command harness bootstrap onto smalltalk. Wires up identity +
// .mcp.json + (harness-specific) session-id + pty registration and
// hands off to the harness binary. Shaped like `ollama launch`.
//
// brief-016 (smalltalk launch): getting a non-Claude harness cleanly
// onto smalltalk previously took multiple fixes; GLM/ollama had an
// unattended-launch gap (interactive model picker). This verb closes
// both. See `notes/harness-integrations.md` for the individual harness
// mechanics — this file is the composition layer.
//
// Design decisions (surfaced in the PR desc so cos can walk):
//   - --model routes through `ollama launch <harness> --model <spec>`.
//     Chose ollama's --model flag over env-extraction: cleaner UX,
//     less brittle.
//   - Skip-if-exists on .claude-session-id and pty.toml. --force to
//     overwrite (never generated a --force flag; the safer default
//     is what we ship). Users can `rm` these to re-bootstrap.
//   - Bare harness name as pty session key (`claude` / `codex`);
//     pty.toml's `prefix` field handles the `<repo>-` prefix.
//   - claude defaults to channel mode (has UI for it); codex defaults
//     to non-channel + a `coord ding` sidecar (no asyncRewake).

import { spawn, spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';

import type { CliContext } from '../cli-context.ts';
import {
  coordRootFrom,
  ensureIdentityDirs,
  envAgentFrom,
  rand6,
} from '../common.ts';
import { cmdInit, resolveCoordBinPath } from './init.ts';

// ─── Shape ──────────────────────────────────────────────────────────────

export type Harness = 'claude' | 'codex';

export interface LaunchInput {
  harness: Harness;
  /** Override the resolved identity. */
  identity?: string | undefined;
  /**
   * When set, route the launch through `ollama launch <harness>
   * --model <spec>` so ollama does the env injection + skips its
   * interactive model picker. Path to unattended GLM-backed agents.
   */
  model?: string | undefined;
  /** When true, don't register via pty even if `pty` is on PATH. */
  noPty?: boolean | undefined;
  /** When true, skip `--channel` on the MCP wiring. Default for claude
   *  is channel-on; for codex is channel-off (codex has no channel UI). */
  noChannel?: boolean | undefined;
  /** Override the pty session name (default: harness name). */
  sessionName?: string | undefined;
  /** When true, print what would happen; touch nothing on disk / no
   *  process spawn. */
  dryRun?: boolean | undefined;

  /** Working directory. Default: process.cwd(). */
  cwd?: string | undefined;
  /** Test seam: override the pty detection. */
  ptyBinPath?: string | undefined;
  /** Test seam: override HOME. */
  home?: string | undefined;
  /** Test seam: skip the actual spawn; return the constructed argv. */
  captureOnly?: boolean | undefined;

  env: NodeJS.ProcessEnv;
  coordRoot: string;
}

export interface LaunchResult {
  identity: string;
  identityAutoGenerated: boolean;
  channel: boolean;
  usedPty: boolean;
  usedOllama: boolean;
  /** The argv the underlying process was (or would be) launched with. */
  argv: readonly string[];
  /** Path to the .mcp.json that was written (or would be). */
  mcpJsonPath: string;
  /** Path to pty.toml if we wrote one, else null. */
  ptyTomlPath: string | null;
  /** Path to .claude-session-id if we wrote one, else null. */
  claudeSessionIdPath: string | null;
  /** Text of pty.toml when running --dry-run, else null. */
  ptyTomlPreview: string | null;
}

// ─── Helpers ────────────────────────────────────────────────────────────

const ANON_PREFIX = 'anon-';

function generateAnonAgent(): string {
  return `${ANON_PREFIX}${rand6()}`;
}

function detectPtyPath(explicitOverride?: string | undefined): string | null {
  if (explicitOverride !== undefined) {
    return explicitOverride.length > 0 ? explicitOverride : null;
  }
  try {
    const r = spawnSync('which', ['pty'], { encoding: 'utf8' });
    if (r.status === 0 && typeof r.stdout === 'string') {
      const found = r.stdout.trim();
      if (found.length > 0 && existsSync(found)) return found;
    }
  } catch {
    // ignore
  }
  return null;
}

/**
 * Encode a working directory the same way Claude Code does when it
 * decides where under `~/.claude/projects/` to write its jsonl.
 * `pty-claude-launcher.sh` uses `tr '/.' '--'`; we mirror it.
 */
function encodedCwd(cwd: string): string {
  return cwd.replace(/[/.]/g, '-');
}

function newUuid(): string {
  // Use node:crypto's randomUUID rather than shelling out to uuidgen
  // (which the reference `pty-claude-launcher.sh` does — we avoid the
  // extra subprocess). Imported statically at the top of this module
  // because the file runs under ESM (`"type": "module"` + `node
  // --experimental-strip-types`) and CJS `require()` is unavailable.
  return randomUUID();
}

// ─── Command construction ──────────────────────────────────────────────

/**
 * Build the claude launch argv, mirroring pty-claude-launcher.sh's
 * jsonl-bootstrap + `--resume <SID>` handoff. When `bootstrapWithPrint`
 * is true, the *caller* is responsible for running a one-shot
 * `claude --print --session-id <SID> "session init"` before the main
 * argv — we return both parts.
 */
function buildClaudeCommand(opts: {
  cwd: string;
  home: string;
  channel: boolean;
  claudeSessionId: string;
}): {
  bootstrapArgv: readonly string[] | null;
  mainArgv: readonly string[];
  jsonlPath: string;
} {
  const encoded = encodedCwd(opts.cwd);
  const jsonlPath = join(
    opts.home,
    '.claude',
    'projects',
    encoded,
    `${opts.claudeSessionId}.jsonl`
  );
  const channelFlag = opts.channel
    ? ['--dangerously-load-development-channels', 'server:st']
    : [];
  const mainArgv = [
    'claude',
    '--permission-mode',
    'auto',
    ...channelFlag,
    '--resume',
    opts.claudeSessionId,
  ] as const;
  // Bootstrap fires only when the jsonl is missing; caller checks
  // `existsSync(jsonlPath)`.
  const bootstrapArgv = [
    'claude',
    '--print',
    '--permission-mode',
    'auto',
    '--session-id',
    opts.claudeSessionId,
    'session init',
  ] as const;
  return { bootstrapArgv, mainArgv, jsonlPath };
}

function buildOllamaCommand(
  harness: Harness,
  model: string
): readonly string[] {
  return ['ollama', 'launch', harness, '--model', model];
}

function buildCodexCommand(cwd: string): readonly string[] {
  const idFile = join(cwd, '.codex-session-id');
  if (existsSync(idFile)) {
    const sid = readFileSync(idFile, 'utf8').trim();
    if (sid.length > 0) return ['codex', 'resume', sid];
  }
  return ['codex'];
}

// ─── pty.toml generation ───────────────────────────────────────────────

/**
 * Quote a single argv element for a shell command line. Elements with
 * no unsafe chars pass through bare; anything else gets single-quoted
 * with embedded single quotes escaped as `'\''`. Not exhaustive but
 * safe for our known argv shapes (harness flags + UUID + model spec).
 */
function shellQuote(a: string): string {
  if (/^[a-zA-Z0-9_\-./:@=+,]+$/.test(a)) return a;
  return `'${a.replace(/'/g, `'\\''`)}'`;
}

/**
 * TOML-escape a bare string for insertion into a `"..."` value. TOML
 * requires backslash-escapes for `\"` and `\\`, and permits others.
 */
function tomlEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function buildPtyToml(opts: {
  harness: Harness;
  sessionName: string;
  identity: string;
  invocation: readonly string[];
  addDingSidecar: boolean;
  cwd: string;
}): string {
  // pty runs `command` via `sh -c`, so produce a shell command line by
  // space-joining shell-quoted argv elements. Then TOML-quote the
  // whole thing for the `command = "..."` value.
  const shellLine = opts.invocation.map(shellQuote).join(' ');
  const prefix = resolveRepoPrefix(opts.cwd);
  const lines: string[] = [];
  lines.push(`prefix = "${tomlEscape(prefix)}"`);
  lines.push('');
  lines.push(`[sessions.${opts.sessionName}]`);
  lines.push(`command = "${tomlEscape(shellLine)}"`);
  lines.push(`tags = { role = "agent" }`);
  lines.push('');
  lines.push(`[sessions.${opts.sessionName}.env]`);
  lines.push(`ST_AGENT = "${tomlEscape(opts.identity)}"`);
  if (opts.addDingSidecar) {
    const dingLine = `coord ding ${shellQuote(opts.sessionName)} --identity ${shellQuote(opts.identity)}`;
    lines.push('');
    lines.push(`[sessions.ding]`);
    lines.push(`command = "${tomlEscape(dingLine)}"`);
    lines.push(`tags = { role = "ding", strategy = "permanent" }`);
    lines.push('');
    lines.push(`[sessions.ding.env]`);
    lines.push(`ST_AGENT = "${tomlEscape(opts.identity)}"`);
  }
  return lines.join('\n') + '\n';
}

function resolveRepoPrefix(cwd: string): string {
  // Fallback: basename of cwd, sanitized to agent grammar (lowercase,
  // hyphens, periods). This mirrors the pty prefix convention Nathan
  // uses for smalltalk / pty / etc.
  const base = cwd.split('/').filter((s) => s.length > 0).pop() ?? 'agent';
  return base
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'agent';
}

// ─── Core ──────────────────────────────────────────────────────────────

export async function cmdLaunch(
  input: LaunchInput,
  ctx: CliContext
): Promise<LaunchResult> {
  const cwd = input.cwd ?? process.cwd();
  const home = input.home ?? homedir();
  const harness = input.harness;

  // ─── Identity resolution ────────────────────────────────────────────
  let identity: string;
  let identityAutoGenerated = false;
  if (input.identity !== undefined && input.identity.length > 0) {
    identity = input.identity;
  } else {
    const fromEnv = envAgentFrom(input.env);
    if (fromEnv !== undefined && fromEnv.length > 0) {
      identity = fromEnv;
    } else {
      identity = generateAnonAgent();
      identityAutoGenerated = true;
      ctx.stderr(
        `[smalltalk] no ST_AGENT set; using throwaway identity ${identity} ` +
          `(set ST_AGENT to persist)\n`
      );
    }
  }
  // Lazy-create the agent's inbox/archive so channel watcher + status
  // writer have something to point at.
  if (!input.dryRun) {
    ensureIdentityDirs(identity, input.coordRoot);
  }

  // ─── .mcp.json bootstrap (via cmdInit) ──────────────────────────────
  const channel =
    input.noChannel === true ? false : harness === 'claude';
  const mcpJsonPath = join(cwd, '.mcp.json');
  if (!input.dryRun) {
    await cmdInit(
      {
        dir: cwd,
        noChannel: !channel,
        force: false,
        // promptAnswer: undefined — leave the existing prompt-gate
        // behavior; a divergent .mcp.json aborts rather than silently
        // overwriting.
      },
      ctx
    );
  }

  // ─── claude session-id bootstrap ────────────────────────────────────
  let claudeSessionIdPath: string | null = null;
  let claudeSessionId: string | null = null;
  if (harness === 'claude') {
    const idFile = join(cwd, '.claude-session-id');
    claudeSessionIdPath = idFile;
    if (existsSync(idFile)) {
      claudeSessionId = readFileSync(idFile, 'utf8').trim();
    }
    if (
      (claudeSessionId === null || claudeSessionId.length === 0) &&
      !input.dryRun
    ) {
      claudeSessionId = newUuid();
      writeFileSync(idFile, `${claudeSessionId}\n`);
    } else if (claudeSessionId === null) {
      claudeSessionId = '<generated-at-runtime>';
    }
  }

  // ─── Command construction ──────────────────────────────────────────
  let argv: readonly string[];
  let usedOllama = false;
  let claudeBootstrapArgv: readonly string[] | null = null;
  let claudeJsonlPath: string | null = null;
  if (input.model !== undefined && input.model.length > 0) {
    // Route through ollama — its `--model` flag skips the interactive
    // picker AND injects env vars claude/codex need to hit the
    // ollama-hosted model.
    argv = buildOllamaCommand(harness, input.model);
    usedOllama = true;
  } else if (harness === 'claude') {
    const built = buildClaudeCommand({
      cwd,
      home,
      channel,
      claudeSessionId: claudeSessionId ?? '<generated-at-runtime>',
    });
    argv = built.mainArgv;
    claudeBootstrapArgv = built.bootstrapArgv;
    claudeJsonlPath = built.jsonlPath;
  } else {
    argv = buildCodexCommand(cwd);
  }

  // ─── pty registration decision ─────────────────────────────────────
  const ptyPath = input.noPty === true ? null : detectPtyPath(input.ptyBinPath);
  const usedPty = ptyPath !== null;
  const sessionName = input.sessionName ?? harness;
  const ptyTomlPath = join(cwd, 'pty.toml');
  let ptyTomlPreview: string | null = null;
  if (usedPty) {
    const preview = buildPtyToml({
      harness,
      sessionName,
      identity,
      invocation: argv,
      addDingSidecar: harness === 'codex',
      cwd,
    });
    ptyTomlPreview = preview;
    if (!input.dryRun && !existsSync(ptyTomlPath)) {
      writeFileSync(ptyTomlPath, preview);
    }
    // else: skip-if-exists. User can `rm pty.toml` to re-bootstrap.
  } else {
    // Emit a suggested pty.toml even when pty isn't present so the
    // user can install pty later and drop it in.
    ptyTomlPreview = buildPtyToml({
      harness,
      sessionName,
      identity,
      invocation: argv,
      addDingSidecar: harness === 'codex',
      cwd,
    });
  }

  // ─── Dry-run / captureOnly short-circuit ───────────────────────────
  if (input.dryRun === true || input.captureOnly === true) {
    return {
      identity,
      identityAutoGenerated,
      channel,
      usedPty,
      usedOllama,
      argv,
      mcpJsonPath,
      ptyTomlPath: usedPty ? ptyTomlPath : null,
      claudeSessionIdPath,
      ptyTomlPreview,
    };
  }

  // ─── Claude bootstrap (jsonl init) ─────────────────────────────────
  // Only fires when the jsonl is missing AND we're going through the
  // direct claude path (not ollama).
  if (
    harness === 'claude' &&
    !usedOllama &&
    claudeBootstrapArgv !== null &&
    claudeJsonlPath !== null &&
    !existsSync(claudeJsonlPath)
  ) {
    ctx.stderr(
      `[smalltalk launch] bootstrapping claude jsonl at ${claudeJsonlPath}\n`
    );
    spawnSync(claudeBootstrapArgv[0]!, claudeBootstrapArgv.slice(1), {
      stdio: ['ignore', 'ignore', 'ignore'],
      env: {
        ...input.env,
        ST_AGENT: identity,
      },
    });
    // Ignore result — the bootstrap is best-effort. If it failed, the
    // main --resume will surface the error next.
  }

  // ─── Spawn ─────────────────────────────────────────────────────────
  const spawnEnv = {
    ...input.env,
    ST_AGENT: identity,
  };
  if (usedPty && ptyPath !== null) {
    // pty picks the sessions up from pty.toml. Exec pty up + wait.
    const child = spawn(ptyPath, ['up'], {
      stdio: 'inherit',
      env: spawnEnv,
      cwd,
    });
    await new Promise<void>((resolvePromise) => {
      child.on('exit', () => resolvePromise());
    });
  } else {
    // Direct spawn of the harness. `stdio: inherit` gives the user
    // the terminal.
    const child = spawn(argv[0]!, argv.slice(1), {
      stdio: 'inherit',
      env: spawnEnv,
      cwd,
    });
    await new Promise<void>((resolvePromise) => {
      child.on('exit', () => resolvePromise());
    });
  }

  return {
    identity,
    identityAutoGenerated,
    channel,
    usedPty,
    usedOllama,
    argv,
    mcpJsonPath,
    ptyTomlPath: usedPty ? ptyTomlPath : null,
    claudeSessionIdPath,
    ptyTomlPreview,
  };
}

// ─── CLI wrapper ────────────────────────────────────────────────────────

const LAUNCH_HELP =
  'usage: st launch <claude|codex> [options]\n\n' +
  '  Stand up an agent wired to smalltalk in one command. Sets up\n' +
  '  identity, .mcp.json, session-id (claude only), and optionally\n' +
  '  registers the session via pty when it is on PATH.\n\n' +
  '  --identity <name>       Explicit agent name. Else $ST_AGENT (with\n' +
  '                          legacy ST_IDENTITY / COORD_IDENTITY chain),\n' +
  '                          else a throwaway anon-<rand6>.\n' +
  '  --model <spec>          Route through `ollama launch <harness>\n' +
  '                          --model <spec>` — skips ollama\'s interactive\n' +
  '                          model picker, unblocks unattended GLM launches.\n' +
  '  --no-channel            Skip the --channel MCP wiring. Default for\n' +
  '                          claude is channel-on; for codex is channel-off.\n' +
  '  --no-pty                Don\'t register via pty even if it is on PATH.\n' +
  '  --session-name <name>   Override pty session key. Default: harness name.\n' +
  '  --dry-run               Print what would happen; touch nothing.\n' +
  '  --print                 Alias for --dry-run.\n\n' +
  '  Examples:\n' +
  '    st launch claude                              # anon identity, channel mode\n' +
  '    st launch claude --identity alice             # persistent identity\n' +
  '    st launch codex                               # + coord ding sidecar\n' +
  '    st launch claude --model glm-5.2:cloud        # via ollama, unattended\n' +
  '    st launch codex --dry-run                     # audit before spawn\n';

export async function cmdLaunchCli(
  args: readonly string[],
  ctx: CliContext
): Promise<number> {
  let harness: Harness | undefined;
  let identity: string | undefined;
  let model: string | undefined;
  let noPty = false;
  let noChannel = false;
  let sessionName: string | undefined;
  let dryRun = false;
  for (let i = 0; i < args.length; i++) {
    const a = args[i]!;
    switch (a) {
      case '-h':
      case '--help':
        ctx.stderr(LAUNCH_HELP);
        return 0;
      case '--identity':
        identity = args[++i];
        break;
      case '--model':
        model = args[++i];
        break;
      case '--no-pty':
        noPty = true;
        break;
      case '--no-channel':
        noChannel = true;
        break;
      case '--session-name':
        sessionName = args[++i];
        break;
      case '--dry-run':
      case '--print':
        dryRun = true;
        break;
      default:
        if (a.startsWith('-')) throw new Error(`unknown flag: ${a}`);
        if (harness === undefined) {
          if (a !== 'claude' && a !== 'codex') {
            throw new Error(
              `unknown harness: ${a} (supported: claude, codex)`
            );
          }
          harness = a;
        } else {
          throw new Error(`unexpected arg: ${a}`);
        }
    }
  }
  if (harness === undefined) {
    ctx.stderr(LAUNCH_HELP);
    return 2;
  }

  const r = await cmdLaunch(
    {
      harness,
      ...(identity !== undefined && { identity }),
      ...(model !== undefined && { model }),
      noPty,
      noChannel,
      ...(sessionName !== undefined && { sessionName }),
      dryRun,
      env: ctx.env,
      coordRoot: ctx.coordRoot,
    },
    ctx
  );

  if (dryRun) {
    // Human-readable summary for --dry-run.
    ctx.stdout(`identity:       ${r.identity}\n`);
    if (r.identityAutoGenerated) {
      ctx.stdout(`                (throwaway; set ST_AGENT to persist)\n`);
    }
    ctx.stdout(`channel mode:   ${r.channel ? 'on' : 'off'}\n`);
    ctx.stdout(`ollama route:   ${r.usedOllama ? 'yes' : 'no'}\n`);
    ctx.stdout(`pty available:  ${r.usedPty ? 'yes' : 'no'}\n`);
    ctx.stdout(`mcp.json:       ${r.mcpJsonPath}\n`);
    if (r.claudeSessionIdPath !== null) {
      ctx.stdout(`session id:     ${r.claudeSessionIdPath}\n`);
    }
    ctx.stdout(`\nharness argv:\n  ${r.argv.join(' ')}\n`);
    if (r.ptyTomlPreview !== null) {
      const heading = r.usedPty
        ? `\npty.toml (would write to ${r.ptyTomlPath}):`
        : `\npty.toml (pty not on PATH; write this file by hand if you want it):`;
      ctx.stdout(`${heading}\n${r.ptyTomlPreview}`);
    }
    return 0;
  }
  return 0;
}

// Keep resolveCoordBinPath reachable for `notes/harness-integrations.md`
// linkage; also used by the tests that mock cmdInit.
export { resolveCoordBinPath };
