// commands/launch.ts — `smalltalk launch <claude|codex>` verb.
//
// One-command harness bootstrap onto smalltalk. Wires up identity +
// .mcp.json + (harness-specific) session-id + pty registration and
// hands off to the harness binary. Shaped like `ollama launch`.
//
// brief-016 (smalltalk launch): getting a non-Claude harness cleanly
// onto smalltalk previously took multiple fixes; GLM/ollama had an
// unattended-launch gap (interactive model picker). This verb closes
// both. See `notes/harness-integrations.md` for the individual harness
// mechanics — this file is the composition layer.
//
// Design decisions (surfaced in the PR desc so cos can walk):
//   - --model routes through `ollama launch <harness> --model <spec>`.
//     Chose ollama's --model flag over env-extraction: cleaner UX,
//     less brittle.
//   - Skip-if-exists on .claude-session-id and pty.toml. --force to
//     overwrite (never generated a --force flag; the safer default
//     is what we ship). Users can `rm` these to re-bootstrap.
//   - Bare harness name as pty session key (`claude` / `codex`);
//     pty.toml's `prefix` field handles the `<repo>-` prefix.
//   - claude defaults to channel mode (has UI for it); codex defaults
//     to non-channel + a `coord ding` sidecar (no asyncRewake).

import { spawn, spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';

import type { CliContext } from '../cli-context.ts';
import {
  coordRootFrom,
  ensureIdentityDirs,
  envAgentFrom,
  rand6,
} from '../common.ts';
import { cmdInit, resolveCoordBinPath } from './init.ts';

// ─── Shape ──────────────────────────────────────────────────────────────

export type Harness = 'claude' | 'codex';

export interface LaunchInput {
  harness: Harness;
  /** Override the resolved identity. */
  identity?: string | undefined;
  /**
   * When set, route the launch through `ollama launch <harness>
   * --model <spec>` so ollama does the env injection + skips its
   * interactive model picker. Path to unattended GLM-backed agents.
   */
  model?: string | undefined;
  /** When true, don't register via pty even if `pty` is on PATH. */
  noPty?: boolean | undefined;
  /** When true, skip `--channel` on the MCP wiring. Default for claude
   *  is channel-on; for codex is channel-off (codex has no channel UI). */
  noChannel?: boolean | undefined;
  /** Override the pty session name (default: harness name). */
  sessionName?: string | undefined;
  /** When true, print what would happen; touch nothing on disk / no
   *  process spawn. */
  dryRun?: boolean | undefined;

  /**
   * brief-022: install a persona alongside the harness. The path is
   * copied to `<cwd>/PERSONA.md`, and the harness entry file
   * (`CLAUDE.md` for claude, `AGENTS.md` for codex) gets a
   * `@PERSONA.md` import line surgically appended if not already
   * present. Both harnesses support the `@`-import mechanism
   * (verified 2026-07-02 against codex 0.142.4 + claude 2.1.198).
   * We git-exclude the infra we generate via `.git/info/exclude` so
   * the persona doesn't pollute the target repo's commits.
   *
   * When the entry file didn't exist and we created it, that file
   * gets excluded too; when it pre-existed (a real repo CLAUDE.md /
   * AGENTS.md), it's left in the repo untouched — only the appended
   * line adds an ignored import.
   */
  persona?: string | undefined;

  /** Working directory. Default: process.cwd(). */
  cwd?: string | undefined;
  /** Test seam: override the pty detection. */
  ptyBinPath?: string | undefined;
  /** Test seam: override HOME. */
  home?: string | undefined;
  /** Test seam: skip the actual spawn; return the constructed argv. */
  captureOnly?: boolean | undefined;

  env: NodeJS.ProcessEnv;
  coordRoot: string;
}

export interface LaunchResult {
  identity: string;
  identityAutoGenerated: boolean;
  channel: boolean;
  usedPty: boolean;
  usedOllama: boolean;
  /** The argv the underlying process was (or would be) launched with. */
  argv: readonly string[];
  /** Path to the .mcp.json that was written (or would be). */
  mcpJsonPath: string;
  /** Path to pty.toml if we wrote one, else null. */
  ptyTomlPath: string | null;
  /** Path to .claude-session-id if we wrote one, else null. */
  claudeSessionIdPath: string | null;
  /** Text of pty.toml when running --dry-run, else null. */
  ptyTomlPreview: string | null;
  /**
   * brief-022: summary of the persona install, or null when
   * `--persona` was not passed. Populated in both real-run and
   * `--dry-run` mode so tests + CLI dry-run output can inspect the
   * decisions we would make without touching disk.
   */
  persona: PersonaInstallResult | null;
}

/**
 * brief-022: what {@link cmdLaunch} decided to do with the persona
 * install. All fields are populated regardless of --dry-run — a
 * dry-run just skips the actual file I/O and git-exclude append. The
 * `entryFileCreated` flag drives the exclusion decision: only files we
 * created get excluded, so a pre-existing repo CLAUDE.md never gets
 * added to the ignore list.
 */
export interface PersonaInstallResult {
  /** Path we would (or did) copy the persona source to. */
  personaMdPath: string;
  /** `CLAUDE.md` (claude harness) or `AGENTS.md` (codex harness). */
  entryFile: 'CLAUDE.md' | 'AGENTS.md';
  /** Absolute path to the entry file. */
  entryFilePath: string;
  /** True when the entry file didn't exist and we created it. */
  entryFileCreated: boolean;
  /** True when we appended a `@PERSONA.md` line (vs. it was already
   *  present). */
  importLineAppended: boolean;
  /** Entries that were (or would be) appended to `.git/info/exclude`. */
  gitExcludeEntriesAdded: readonly string[];
  /** True when the target cwd was not a git repo, so we couldn't
   *  exclude. Callers can surface a warning; the persona still
   *  installs. */
  gitRepoAbsent: boolean;
}

// ─── Helpers ────────────────────────────────────────────────────────────

const ANON_PREFIX = 'anon-';

function generateAnonAgent(): string {
  return `${ANON_PREFIX}${rand6()}`;
}

function detectPtyPath(explicitOverride?: string | undefined): string | null {
  if (explicitOverride !== undefined) {
    return explicitOverride.length > 0 ? explicitOverride : null;
  }
  try {
    const r = spawnSync('which', ['pty'], { encoding: 'utf8' });
    if (r.status === 0 && typeof r.stdout === 'string') {
      const found = r.stdout.trim();
      if (found.length > 0 && existsSync(found)) return found;
    }
  } catch {
    // ignore
  }
  return null;
}

/**
 * Encode a working directory the same way Claude Code does when it
 * decides where under `~/.claude/projects/` to write its jsonl.
 * `pty-claude-launcher.sh` uses `tr '/.' '--'`; we mirror it.
 */
function encodedCwd(cwd: string): string {
  return cwd.replace(/[/.]/g, '-');
}

function newUuid(): string {
  // Use node:crypto's randomUUID rather than shelling out to uuidgen
  // (which the reference `pty-claude-launcher.sh` does — we avoid the
  // extra subprocess). Imported statically at the top of this module
  // because the file runs under ESM (`"type": "module"` + `node
  // --experimental-strip-types`) and CJS `require()` is unavailable.
  return randomUUID();
}

// ─── Command construction ──────────────────────────────────────────────

/**
 * Build the claude launch argv, mirroring pty-claude-launcher.sh's
 * jsonl-bootstrap + `--resume <SID>` handoff. When `bootstrapWithPrint`
 * is true, the *caller* is responsible for running a one-shot
 * `claude --print --session-id <SID> "session init"` before the main
 * argv — we return both parts.
 */
function buildClaudeCommand(opts: {
  cwd: string;
  home: string;
  channel: boolean;
  claudeSessionId: string;
}): {
  bootstrapArgv: readonly string[] | null;
  mainArgv: readonly string[];
  jsonlPath: string;
} {
  const encoded = encodedCwd(opts.cwd);
  const jsonlPath = join(
    opts.home,
    '.claude',
    'projects',
    encoded,
    `${opts.claudeSessionId}.jsonl`
  );
  const channelFlag = opts.channel
    ? ['--dangerously-load-development-channels', 'server:st']
    : [];
  const mainArgv = [
    'claude',
    '--permission-mode',
    'auto',
    ...channelFlag,
    '--resume',
    opts.claudeSessionId,
  ] as const;
  // Bootstrap fires only when the jsonl is missing; caller checks
  // `existsSync(jsonlPath)`.
  const bootstrapArgv = [
    'claude',
    '--print',
    '--permission-mode',
    'auto',
    '--session-id',
    opts.claudeSessionId,
    'session init',
  ] as const;
  return { bootstrapArgv, mainArgv, jsonlPath };
}

function buildOllamaCommand(
  harness: Harness,
  model: string
): readonly string[] {
  return ['ollama', 'launch', harness, '--model', model];
}

function buildCodexCommand(cwd: string): readonly string[] {
  const idFile = join(cwd, '.codex-session-id');
  if (existsSync(idFile)) {
    const sid = readFileSync(idFile, 'utf8').trim();
    if (sid.length > 0) return ['codex', 'resume', sid];
  }
  return ['codex'];
}

// ─── pty.toml generation ───────────────────────────────────────────────

/**
 * Quote a single argv element for a shell command line. Elements with
 * no unsafe chars pass through bare; anything else gets single-quoted
 * with embedded single quotes escaped as `'\''`. Not exhaustive but
 * safe for our known argv shapes (harness flags + UUID + model spec).
 */
function shellQuote(a: string): string {
  if (/^[a-zA-Z0-9_\-./:@=+,]+$/.test(a)) return a;
  return `'${a.replace(/'/g, `'\\''`)}'`;
}

/**
 * TOML-escape a bare string for insertion into a `"..."` value. TOML
 * requires backslash-escapes for `\"` and `\\`, and permits others.
 */
function tomlEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function buildPtyToml(opts: {
  harness: Harness;
  sessionName: string;
  identity: string;
  invocation: readonly string[];
  addDingSidecar: boolean;
  cwd: string;
}): string {
  // pty runs `command` via `sh -c`, so produce a shell command line by
  // space-joining shell-quoted argv elements. Then TOML-quote the
  // whole thing for the `command = "..."` value.
  const shellLine = opts.invocation.map(shellQuote).join(' ');
  const prefix = resolveRepoPrefix(opts.cwd);
  const lines: string[] = [];
  lines.push(`prefix = "${tomlEscape(prefix)}"`);
  lines.push('');
  lines.push(`[sessions.${opts.sessionName}]`);
  lines.push(`command = "${tomlEscape(shellLine)}"`);
  lines.push(`tags = { role = "agent" }`);
  lines.push('');
  lines.push(`[sessions.${opts.sessionName}.env]`);
  lines.push(`ST_AGENT = "${tomlEscape(opts.identity)}"`);
  if (opts.addDingSidecar) {
    const dingLine = `coord ding ${shellQuote(opts.sessionName)} --identity ${shellQuote(opts.identity)}`;
    lines.push('');
    lines.push(`[sessions.ding]`);
    lines.push(`command = "${tomlEscape(dingLine)}"`);
    lines.push(`tags = { role = "ding", strategy = "permanent" }`);
    lines.push('');
    lines.push(`[sessions.ding.env]`);
    lines.push(`ST_AGENT = "${tomlEscape(opts.identity)}"`);
  }
  return lines.join('\n') + '\n';
}

// ─── brief-022: persona install ────────────────────────────────────────

/** The infra files `st launch` creates in the target cwd. Persona-mode
 *  always excludes these (except entryFile — see below). Kept as an
 *  exported const so the CLI dry-run summary + tests can enumerate the
 *  same list without duplicating it. */
export const PERSONA_ALWAYS_EXCLUDE = [
  'PERSONA.md',
  '.mcp.json',
  '.claude-session-id',
  '.codex-session-id',
  'pty.toml',
] as const;

/** Read the current `.git/info/exclude`, or empty string if missing.
 *  Used both for the "is this line already there?" dedup and for the
 *  final append. Failures (e.g. `.git` isn't a dir) surface as empty. */
function readGitExclude(cwd: string): { path: string; text: string } | null {
  const gitDir = join(cwd, '.git');
  // A bare git repo, worktree, or non-git directory won't have
  // .git/info/. Skip cleanly; callers surface `gitRepoAbsent: true`.
  try {
    const st = statSync(gitDir);
    if (!st.isDirectory()) return null;
  } catch {
    return null;
  }
  const excludePath = join(gitDir, 'info', 'exclude');
  let text = '';
  try {
    text = readFileSync(excludePath, 'utf8');
  } catch {
    // missing is fine; append semantics create it
  }
  return { path: excludePath, text };
}

/**
 * Return the entries from `wanted` that aren't already present as a
 * line in the exclude file. Comparison is line-by-line, trimmed.
 * Comments (leading `#`) are ignored so `# PERSONA.md example` doesn't
 * count as a match.
 */
function missingExcludeEntries(
  excludeText: string,
  wanted: readonly string[]
): string[] {
  const present = new Set<string>();
  for (const rawLine of excludeText.split(/\r?\n/)) {
    const trimmed = rawLine.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    present.add(trimmed);
  }
  return wanted.filter((w) => !present.has(w));
}

/**
 * Append `entries` (one per line) to `.git/info/exclude`. Ensures a
 * trailing newline separates existing content from the append. Creates
 * the file (and its parent `info/` dir) if needed. Idempotent when
 * called with an empty entries list.
 */
function appendGitExclude(
  excludePath: string,
  existingText: string,
  entries: readonly string[]
): void {
  if (entries.length === 0) return;
  mkdirSync(dirname(excludePath), { recursive: true });
  const sep = existingText.length === 0 || existingText.endsWith('\n')
    ? ''
    : '\n';
  const blockHeader =
    existingText.length === 0 ? '' : '# smalltalk-launch persona infra\n';
  const appended = `${sep}${blockHeader}${entries.join('\n')}\n`;
  writeFileSync(excludePath, existingText + appended);
}

/**
 * Decide whether the entry file (`CLAUDE.md` / `AGENTS.md`) needs the
 * `@PERSONA.md` import line appended. Returns a struct with the read
 * text (empty when the file didn't exist), whether we'd create the
 * file, and whether we'd append the import.
 */
function planEntryFileEdit(entryFilePath: string): {
  existingText: string;
  fileExisted: boolean;
  importAlreadyPresent: boolean;
} {
  let existingText = '';
  let fileExisted = false;
  try {
    existingText = readFileSync(entryFilePath, 'utf8');
    fileExisted = true;
  } catch {
    // missing file → we'll create it
  }
  // The import line is a bare `@PERSONA.md` on its own line. We match
  // leniently so `@PERSONA.md ` (trailing space) or `@PERSONA.md #
  // comment` are recognized as already-present. Case-sensitive on
  // purpose — the filename is `PERSONA.md`.
  const importPattern = /^@PERSONA\.md\b/m;
  const importAlreadyPresent = importPattern.test(existingText);
  return { existingText, fileExisted, importAlreadyPresent };
}

/**
 * Do (or plan) the persona install. When `dryRun` is true, returns
 * the plan without touching disk; when false, performs the copy /
 * entry-file edit / git-exclude append. All decisions (including
 * `gitExcludeEntriesAdded`) reflect what actually happens, so the
 * dry-run summary matches a real run byte-for-byte.
 */
function installPersona(opts: {
  personaSourcePath: string;
  cwd: string;
  harness: Harness;
  dryRun: boolean;
}): PersonaInstallResult {
  const { personaSourcePath, cwd, harness, dryRun } = opts;
  const entryFile: PersonaInstallResult['entryFile'] =
    harness === 'claude' ? 'CLAUDE.md' : 'AGENTS.md';
  const entryFilePath = join(cwd, entryFile);
  const personaMdPath = join(cwd, 'PERSONA.md');

  // Read the source persona now so a bad --persona path fails loudly
  // (missing file, unreadable, etc.) before we've touched anything on
  // disk. Content is used both to write PERSONA.md in real-run and to
  // guarantee the source is readable in dry-run.
  const personaText = readFileSync(personaSourcePath, 'utf8');

  const entryPlan = planEntryFileEdit(entryFilePath);
  const importLineToAppend = !entryPlan.importAlreadyPresent;
  const entryFileCreated =
    !entryPlan.fileExisted && importLineToAppend;

  // Compute git-exclude entries. Always exclude PERSONA_ALWAYS_EXCLUDE
  // (only those not already present). Additionally exclude the
  // entryFile if we created it — never exclude a pre-existing repo
  // CLAUDE.md.
  const wantedExcludes: string[] = [...PERSONA_ALWAYS_EXCLUDE];
  if (entryFileCreated) wantedExcludes.push(entryFile);

  const excludeInfo = readGitExclude(cwd);
  const gitRepoAbsent = excludeInfo === null;
  const gitExcludeEntriesAdded = excludeInfo
    ? missingExcludeEntries(excludeInfo.text, wantedExcludes)
    : [];

  if (!dryRun) {
    // Copy the persona source → PERSONA.md. If the file already
    // exists in cwd with different content, we OVERWRITE — this is
    // infra we own, not user content (we git-exclude it), and the
    // caller is telling us the source is authoritative for this
    // launch. copyFileSync preserves nothing about the source's
    // permissions we don't want; markdown is markdown.
    copyFileSync(personaSourcePath, personaMdPath);

    // Entry-file edit. If missing → create with just the import line
    // (+ trailing newline). If present without the import → append
    // "\n@PERSONA.md\n" with a leading blank-line separator when the
    // existing content doesn't already end in a newline.
    if (importLineToAppend) {
      if (!entryPlan.fileExisted) {
        writeFileSync(entryFilePath, '@PERSONA.md\n');
      } else {
        const sep =
          entryPlan.existingText.length === 0 ||
          entryPlan.existingText.endsWith('\n')
            ? ''
            : '\n';
        writeFileSync(
          entryFilePath,
          entryPlan.existingText + sep + '@PERSONA.md\n'
        );
      }
    }

    // Git-exclude append (skips silently when not a git repo).
    if (excludeInfo && gitExcludeEntriesAdded.length > 0) {
      appendGitExclude(
        excludeInfo.path,
        excludeInfo.text,
        gitExcludeEntriesAdded
      );
    }
  }

  // Reference `personaText` so the read isn't optimized away in a
  // future refactor — the read serves as an eager error surface for
  // bad --persona paths, so we want the read to happen before any
  // downstream work does.
  void personaText;

  return {
    personaMdPath,
    entryFile,
    entryFilePath,
    entryFileCreated,
    importLineAppended: importLineToAppend,
    gitExcludeEntriesAdded,
    gitRepoAbsent,
  };
}

function resolveRepoPrefix(cwd: string): string {
  // Fallback: basename of cwd, sanitized to agent grammar (lowercase,
  // hyphens, periods). This mirrors the pty prefix convention Nathan
  // uses for smalltalk / pty / etc.
  const base = cwd.split('/').filter((s) => s.length > 0).pop() ?? 'agent';
  return base
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'agent';
}

// ─── Core ──────────────────────────────────────────────────────────────

export async function cmdLaunch(
  input: LaunchInput,
  ctx: CliContext
): Promise<LaunchResult> {
  const cwd = input.cwd ?? process.cwd();
  const home = input.home ?? homedir();
  const harness = input.harness;

  // ─── Identity resolution ────────────────────────────────────────────
  let identity: string;
  let identityAutoGenerated = false;
  if (input.identity !== undefined && input.identity.length > 0) {
    identity = input.identity;
  } else {
    const fromEnv = envAgentFrom(input.env);
    if (fromEnv !== undefined && fromEnv.length > 0) {
      identity = fromEnv;
    } else {
      identity = generateAnonAgent();
      identityAutoGenerated = true;
      ctx.stderr(
        `[smalltalk] no ST_AGENT set; using throwaway identity ${identity} ` +
          `(set ST_AGENT to persist)\n`
      );
    }
  }
  // Lazy-create the agent's inbox/archive so channel watcher + status
  // writer have something to point at.
  if (!input.dryRun) {
    ensureIdentityDirs(identity, input.coordRoot);
  }

  // ─── .mcp.json bootstrap (via cmdInit) ──────────────────────────────
  const channel =
    input.noChannel === true ? false : harness === 'claude';
  const mcpJsonPath = join(cwd, '.mcp.json');
  if (!input.dryRun) {
    await cmdInit(
      {
        dir: cwd,
        noChannel: !channel,
        force: false,
        // promptAnswer: undefined — leave the existing prompt-gate
        // behavior; a divergent .mcp.json aborts rather than silently
        // overwriting.
      },
      ctx
    );
  }

  // ─── brief-022: persona install ─────────────────────────────────────
  // Runs BEFORE session-id / command construction so the entry file
  // (CLAUDE.md/AGENTS.md) is in place before the harness process
  // reads it. Both dry-run and real-run go through `installPersona` —
  // the returned plan is what we display in --dry-run and what we
  // actually did in real-run; only the file I/O differs internally.
  let personaResult: PersonaInstallResult | null = null;
  if (input.persona !== undefined && input.persona.length > 0) {
    const source = isAbsolute(input.persona)
      ? input.persona
      : resolve(process.cwd(), input.persona);
    try {
      personaResult = installPersona({
        personaSourcePath: source,
        cwd,
        harness,
        dryRun: input.dryRun === true,
      });
    } catch (err) {
      // Surface a clean error that names the flag and the source
      // path rather than the raw ENOENT — the caller almost always
      // wants to know "where did you look?"
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(
        `--persona: could not read persona file at ${source}: ${msg}`
      );
    }
    if (personaResult.gitRepoAbsent) {
      ctx.stderr(
        `[smalltalk launch] --persona: ${cwd} is not a git repo; ` +
          `skipping .git/info/exclude update. The persona files are ` +
          `still installed.\n`
      );
    }
  }

  // ─── claude session-id bootstrap ────────────────────────────────────
  let claudeSessionIdPath: string | null = null;
  let claudeSessionId: string | null = null;
  if (harness === 'claude') {
    const idFile = join(cwd, '.claude-session-id');
    claudeSessionIdPath = idFile;
    if (existsSync(idFile)) {
      claudeSessionId = readFileSync(idFile, 'utf8').trim();
    }
    if (
      (claudeSessionId === null || claudeSessionId.length === 0) &&
      !input.dryRun
    ) {
      claudeSessionId = newUuid();
      writeFileSync(idFile, `${claudeSessionId}\n`);
    } else if (claudeSessionId === null) {
      claudeSessionId = '<generated-at-runtime>';
    }
  }

  // ─── Command construction ──────────────────────────────────────────
  let argv: readonly string[];
  let usedOllama = false;
  let claudeBootstrapArgv: readonly string[] | null = null;
  let claudeJsonlPath: string | null = null;
  if (input.model !== undefined && input.model.length > 0) {
    // Route through ollama — its `--model` flag skips the interactive
    // picker AND injects env vars claude/codex need to hit the
    // ollama-hosted model.
    argv = buildOllamaCommand(harness, input.model);
    usedOllama = true;
  } else if (harness === 'claude') {
    const built = buildClaudeCommand({
      cwd,
      home,
      channel,
      claudeSessionId: claudeSessionId ?? '<generated-at-runtime>',
    });
    argv = built.mainArgv;
    claudeBootstrapArgv = built.bootstrapArgv;
    claudeJsonlPath = built.jsonlPath;
  } else {
    argv = buildCodexCommand(cwd);
  }

  // ─── pty registration decision ─────────────────────────────────────
  const ptyPath = input.noPty === true ? null : detectPtyPath(input.ptyBinPath);
  const usedPty = ptyPath !== null;
  const sessionName = input.sessionName ?? harness;
  const ptyTomlPath = join(cwd, 'pty.toml');
  let ptyTomlPreview: string | null = null;
  if (usedPty) {
    const preview = buildPtyToml({
      harness,
      sessionName,
      identity,
      invocation: argv,
      addDingSidecar: harness === 'codex',
      cwd,
    });
    ptyTomlPreview = preview;
    if (!input.dryRun && !existsSync(ptyTomlPath)) {
      writeFileSync(ptyTomlPath, preview);
    }
    // else: skip-if-exists. User can `rm pty.toml` to re-bootstrap.
  } else {
    // Emit a suggested pty.toml even when pty isn't present so the
    // user can install pty later and drop it in.
    ptyTomlPreview = buildPtyToml({
      harness,
      sessionName,
      identity,
      invocation: argv,
      addDingSidecar: harness === 'codex',
      cwd,
    });
  }

  // ─── Dry-run / captureOnly short-circuit ───────────────────────────
  if (input.dryRun === true || input.captureOnly === true) {
    return {
      identity,
      identityAutoGenerated,
      channel,
      usedPty,
      usedOllama,
      argv,
      mcpJsonPath,
      ptyTomlPath: usedPty ? ptyTomlPath : null,
      claudeSessionIdPath,
      ptyTomlPreview,
      persona: personaResult,
    };
  }

  // ─── Claude bootstrap (jsonl init) ─────────────────────────────────
  // Only fires when the jsonl is missing AND we're going through the
  // direct claude path (not ollama).
  if (
    harness === 'claude' &&
    !usedOllama &&
    claudeBootstrapArgv !== null &&
    claudeJsonlPath !== null &&
    !existsSync(claudeJsonlPath)
  ) {
    ctx.stderr(
      `[smalltalk launch] bootstrapping claude jsonl at ${claudeJsonlPath}\n`
    );
    spawnSync(claudeBootstrapArgv[0]!, claudeBootstrapArgv.slice(1), {
      stdio: ['ignore', 'ignore', 'ignore'],
      env: {
        ...input.env,
        ST_AGENT: identity,
      },
    });
    // Ignore result — the bootstrap is best-effort. If it failed, the
    // main --resume will surface the error next.
  }

  // ─── Spawn ─────────────────────────────────────────────────────────
  const spawnEnv = {
    ...input.env,
    ST_AGENT: identity,
  };
  if (usedPty && ptyPath !== null) {
    // pty picks the sessions up from pty.toml. Exec pty up + wait.
    const child = spawn(ptyPath, ['up'], {
      stdio: 'inherit',
      env: spawnEnv,
      cwd,
    });
    await new Promise<void>((resolvePromise) => {
      child.on('exit', () => resolvePromise());
    });
  } else {
    // Direct spawn of the harness. `stdio: inherit` gives the user
    // the terminal.
    const child = spawn(argv[0]!, argv.slice(1), {
      stdio: 'inherit',
      env: spawnEnv,
      cwd,
    });
    await new Promise<void>((resolvePromise) => {
      child.on('exit', () => resolvePromise());
    });
  }

  return {
    identity,
    identityAutoGenerated,
    channel,
    usedPty,
    usedOllama,
    argv,
    mcpJsonPath,
    ptyTomlPath: usedPty ? ptyTomlPath : null,
    claudeSessionIdPath,
    ptyTomlPreview,
    persona: personaResult,
  };
}

// ─── CLI wrapper ────────────────────────────────────────────────────────

const LAUNCH_HELP =
  'usage: st launch <claude|codex> [options]\n\n' +
  '  Stand up an agent wired to smalltalk in one command. Sets up\n' +
  '  identity, .mcp.json, session-id (claude only), and optionally\n' +
  '  registers the session via pty when it is on PATH.\n\n' +
  '  --identity <name>       Explicit agent name. Else $ST_AGENT (with\n' +
  '                          legacy ST_IDENTITY / COORD_IDENTITY chain),\n' +
  '                          else a throwaway anon-<rand6>.\n' +
  '  --model <spec>          Route through `ollama launch <harness>\n' +
  '                          --model <spec>` — skips ollama\'s interactive\n' +
  '                          model picker, unblocks unattended GLM launches.\n' +
  '  --no-channel            Skip the --channel MCP wiring. Default for\n' +
  '                          claude is channel-on; for codex is channel-off.\n' +
  '  --no-pty                Don\'t register via pty even if it is on PATH.\n' +
  '  --session-name <name>   Override pty session key. Default: harness name.\n' +
  '  --persona <path>        Install <path> as PERSONA.md and surgically\n' +
  '                          add `@PERSONA.md` to CLAUDE.md (claude) or\n' +
  '                          AGENTS.md (codex). Pre-existing entry files\n' +
  '                          are NEVER clobbered — only the import line\n' +
  '                          is appended if not already present. Infra we\n' +
  '                          create is added to `.git/info/exclude` so it\n' +
  '                          stays out of the repo.\n' +
  '  --dry-run               Print what would happen; touch nothing.\n' +
  '  --print                 Alias for --dry-run.\n\n' +
  '  Examples:\n' +
  '    st launch claude                              # anon identity, channel mode\n' +
  '    st launch claude --identity alice             # persistent identity\n' +
  '    st launch codex                               # + coord ding sidecar\n' +
  '    st launch claude --model glm-5.2:cloud        # via ollama, unattended\n' +
  '    st launch codex --dry-run                     # audit before spawn\n';

export async function cmdLaunchCli(
  args: readonly string[],
  ctx: CliContext
): Promise<number> {
  let harness: Harness | undefined;
  let identity: string | undefined;
  let model: string | undefined;
  let noPty = false;
  let noChannel = false;
  let sessionName: string | undefined;
  let persona: string | undefined;
  let dryRun = false;
  for (let i = 0; i < args.length; i++) {
    const a = args[i]!;
    switch (a) {
      case '-h':
      case '--help':
        ctx.stderr(LAUNCH_HELP);
        return 0;
      case '--identity':
        identity = args[++i];
        break;
      case '--model':
        model = args[++i];
        break;
      case '--no-pty':
        noPty = true;
        break;
      case '--no-channel':
        noChannel = true;
        break;
      case '--session-name':
        sessionName = args[++i];
        break;
      case '--persona':
        persona = args[++i];
        break;
      case '--dry-run':
      case '--print':
        dryRun = true;
        break;
      default:
        if (a.startsWith('-')) throw new Error(`unknown flag: ${a}`);
        if (harness === undefined) {
          if (a !== 'claude' && a !== 'codex') {
            throw new Error(
              `unknown harness: ${a} (supported: claude, codex)`
            );
          }
          harness = a;
        } else {
          throw new Error(`unexpected arg: ${a}`);
        }
    }
  }
  if (harness === undefined) {
    ctx.stderr(LAUNCH_HELP);
    return 2;
  }

  const r = await cmdLaunch(
    {
      harness,
      ...(identity !== undefined && { identity }),
      ...(model !== undefined && { model }),
      noPty,
      noChannel,
      ...(sessionName !== undefined && { sessionName }),
      ...(persona !== undefined && { persona }),
      dryRun,
      env: ctx.env,
      coordRoot: ctx.coordRoot,
    },
    ctx
  );

  if (dryRun) {
    // Human-readable summary for --dry-run.
    ctx.stdout(`identity:       ${r.identity}\n`);
    if (r.identityAutoGenerated) {
      ctx.stdout(`                (throwaway; set ST_AGENT to persist)\n`);
    }
    ctx.stdout(`channel mode:   ${r.channel ? 'on' : 'off'}\n`);
    ctx.stdout(`ollama route:   ${r.usedOllama ? 'yes' : 'no'}\n`);
    ctx.stdout(`pty available:  ${r.usedPty ? 'yes' : 'no'}\n`);
    ctx.stdout(`mcp.json:       ${r.mcpJsonPath}\n`);
    if (r.claudeSessionIdPath !== null) {
      ctx.stdout(`session id:     ${r.claudeSessionIdPath}\n`);
    }
    ctx.stdout(`\nharness argv:\n  ${r.argv.join(' ')}\n`);
    if (r.ptyTomlPreview !== null) {
      const heading = r.usedPty
        ? `\npty.toml (would write to ${r.ptyTomlPath}):`
        : `\npty.toml (pty not on PATH; write this file by hand if you want it):`;
      ctx.stdout(`${heading}\n${r.ptyTomlPreview}`);
    }
    if (r.persona !== null) {
      // Persona summary — reflect the exact decisions installPersona
      // made, so the operator can eyeball "did we create the entry
      // file? did we edit an existing one? which lines are we adding
      // to git-exclude?" without running for real first.
      ctx.stdout(`\npersona:\n`);
      ctx.stdout(`  copy:         ${r.persona.personaMdPath}\n`);
      const action = r.persona.entryFileCreated
        ? 'create'
        : r.persona.importLineAppended
          ? 'append @PERSONA.md'
          : 'no change (import already present)';
      ctx.stdout(`  entry file:   ${r.persona.entryFilePath} (${action})\n`);
      if (r.persona.gitRepoAbsent) {
        ctx.stdout(
          `  git-exclude:  skipped (${cwdForGitExcludeNote(r)} is not a git repo)\n`
        );
      } else if (r.persona.gitExcludeEntriesAdded.length === 0) {
        ctx.stdout(`  git-exclude:  no new entries (all already present)\n`);
      } else {
        ctx.stdout(
          `  git-exclude:  ${r.persona.gitExcludeEntriesAdded.join(', ')}\n`
        );
      }
    }
    return 0;
  }
  return 0;
}

/** Small helper: extract the target cwd from the launch result path
 *  so we don't need to pass it through separately. All the fields we
 *  care about live under the same cwd, and dirname of the entryFile
 *  is the cleanest source. */
function cwdForGitExcludeNote(r: {
  persona: PersonaInstallResult | null;
}): string {
  return r.persona ? dirname(r.persona.entryFilePath) : '.';
}

// Keep resolveCoordBinPath reachable for `notes/harness-integrations.md`
// linkage; also used by the tests that mock cmdInit.
export { resolveCoordBinPath };
