// tests/unit/launch.test.ts — brief-016 `smalltalk launch` core.
//
// Focus: identity resolution, command-argv construction, pty.toml
// content, dry-run flow. Actual harness spawning is out of scope for
// unit tests — we exercise the captureOnly/dryRun seams that return
// the constructed argv without executing anything.

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import type { CliContext } from '../../src/cli-context.ts';
import { cmdLaunch } from '../../src/commands/launch.ts';

let scratch: string;
let cwd: string;
let coordRoot: string;
let home: string;
let stderrBuf: string;
let stdoutBuf: string;
let ctx: CliContext;

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'st-launch-'));
  cwd = join(scratch, 'repo');
  coordRoot = join(scratch, 'state');
  home = join(scratch, 'home');
  mkdirSync(cwd, { recursive: true });
  mkdirSync(coordRoot, { recursive: true });
  mkdirSync(home, { recursive: true });
  stderrBuf = '';
  stdoutBuf = '';
  ctx = {
    env: {},
    coordRoot,
    coordConfig: '/unused',
    stdout: (s) => {
      stdoutBuf += s;
    },
    stderr: (s) => {
      stderrBuf += s;
    },
    readStdin: async () => Buffer.alloc(0),
  };
});

afterEach(() => {
  rmSync(scratch, { recursive: true, force: true });
});

function baseInput(overrides: Partial<Parameters<typeof cmdLaunch>[0]> = {}) {
  return {
    harness: 'claude' as const,
    cwd,
    home,
    coordRoot,
    env: {} as NodeJS.ProcessEnv,
    dryRun: true,
    ptyBinPath: '', // treat as pty NOT on PATH
    ...overrides,
  };
}

// ─── Identity resolution ───────────────────────────────────────────────

describe('cmdLaunch — identity resolution', () => {
  it('uses --identity when set', async () => {
    const r = await cmdLaunch(baseInput({ identity: 'alice' }), ctx);
    expect(r.identity).toBe('alice');
    expect(r.identityAutoGenerated).toBe(false);
    expect(stderrBuf).not.toMatch(/anon-/);
  });

  it('falls back to $ST_AGENT when --identity is unset', async () => {
    const r = await cmdLaunch(
      baseInput({ env: { ST_AGENT: 'bob' } }),
      ctx
    );
    expect(r.identity).toBe('bob');
    expect(r.identityAutoGenerated).toBe(false);
  });

  it('falls back to $ST_IDENTITY when ST_AGENT unset (deprecation chain)', async () => {
    const r = await cmdLaunch(
      baseInput({ env: { ST_IDENTITY: 'legacy-alice' } }),
      ctx
    );
    expect(r.identity).toBe('legacy-alice');
    expect(r.identityAutoGenerated).toBe(false);
  });

  it('falls back to $COORD_IDENTITY when neither ST_* is set', async () => {
    const r = await cmdLaunch(
      baseInput({ env: { COORD_IDENTITY: 'legacy-coord-bob' } }),
      ctx
    );
    expect(r.identity).toBe('legacy-coord-bob');
    expect(r.identityAutoGenerated).toBe(false);
  });

  it('generates anon-<rand6> when no identity is available', async () => {
    const r = await cmdLaunch(baseInput({}), ctx);
    expect(r.identity).toMatch(/^anon-[0-9a-z]{6}$/);
    expect(r.identityAutoGenerated).toBe(true);
    expect(stderrBuf).toMatch(/no ST_AGENT set/);
    expect(stderrBuf).toMatch(/set ST_AGENT to persist/);
    expect(stderrBuf).toMatch(/anon-[0-9a-z]{6}/);
  });

  it('explicit --identity wins over $ST_AGENT', async () => {
    const r = await cmdLaunch(
      baseInput({ identity: 'explicit', env: { ST_AGENT: 'from-env' } }),
      ctx
    );
    expect(r.identity).toBe('explicit');
  });
});

// ─── Channel-mode defaults ─────────────────────────────────────────────

describe('cmdLaunch — channel mode defaults', () => {
  it('claude defaults to channel-mode on', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'claude' }), ctx);
    expect(r.channel).toBe(true);
    expect(r.argv.join(' ')).toContain(
      '--dangerously-load-development-channels server:st'
    );
  });

  it('codex defaults to channel-mode off', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.channel).toBe(false);
  });

  it('--no-channel disables channel on claude', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', noChannel: true }),
      ctx
    );
    expect(r.channel).toBe(false);
    expect(r.argv.join(' ')).not.toContain(
      '--dangerously-load-development-channels'
    );
  });
});

// ─── Command argv construction ─────────────────────────────────────────

describe('cmdLaunch — command argv', () => {
  it('claude direct path uses --resume with a session id', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.argv[0]).toBe('claude');
    expect(r.argv).toContain('--resume');
    expect(r.argv).toContain('--permission-mode');
    expect(r.argv).toContain('auto');
  });

  it('codex direct path uses `codex resume <sid>` when .codex-session-id exists', async () => {
    writeFileSync(join(cwd, '.codex-session-id'), 'abc-123\n');
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.argv).toEqual(['codex', 'resume', 'abc-123']);
  });

  it('codex direct path is bare `codex` when no .codex-session-id', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.argv).toEqual(['codex']);
  });

  it('--model routes through `ollama launch <harness> --model <spec>`', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', model: 'glm-5.2:cloud' }),
      ctx
    );
    expect(r.argv).toEqual([
      'ollama',
      'launch',
      'claude',
      '--model',
      'glm-5.2:cloud',
    ]);
    expect(r.usedOllama).toBe(true);
  });

  it('--model works for codex too', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', model: 'glm-5.2:cloud' }),
      ctx
    );
    expect(r.argv).toEqual([
      'ollama',
      'launch',
      'codex',
      '--model',
      'glm-5.2:cloud',
    ]);
    expect(r.usedOllama).toBe(true);
  });
});

// ─── brief-023: --permission-mode ─────────────────────────────────────

describe('cmdLaunch — --permission-mode (brief-023)', () => {
  // Sanity anchor: no flag, no env → auto in BOTH bootstrap and main
  // argv. Guards against a future refactor that changes the default
  // silently, which would demote eval-spinner posture back to `auto`
  // for callers that had been relying on the flag override.
  it('defaults to auto when neither flag nor env is set', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.permissionMode).toBe('auto');
    // Main argv has exactly one --permission-mode + auto pair.
    const idx = r.argv.indexOf('--permission-mode');
    expect(idx).toBeGreaterThanOrEqual(0);
    expect(r.argv[idx + 1]).toBe('auto');
  });

  it('explicit --permission-mode overrides everything', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        permissionMode: 'bypassPermissions',
        env: { CLAUDE_PERMISSION_MODE: 'plan' },
      }),
      ctx
    );
    expect(r.permissionMode).toBe('bypassPermissions');
    const idx = r.argv.indexOf('--permission-mode');
    expect(r.argv[idx + 1]).toBe('bypassPermissions');
  });

  it('CLAUDE_PERMISSION_MODE env kicks in when the flag is absent', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        env: { CLAUDE_PERMISSION_MODE: 'bypassPermissions' },
      }),
      ctx
    );
    expect(r.permissionMode).toBe('bypassPermissions');
    const idx = r.argv.indexOf('--permission-mode');
    expect(r.argv[idx + 1]).toBe('bypassPermissions');
  });

  it('empty --permission-mode value falls through to env, then default', async () => {
    // Guard against argv shape `--permission-mode ""` (an operator
    // wired it through a variable that expanded to empty). We treat
    // empty like "unset" so the env / default tier still resolves,
    // rather than passing "" to claude which would reject it.
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        permissionMode: '',
        env: {},
      }),
      ctx
    );
    expect(r.permissionMode).toBe('auto');
  });

  it('mode is baked into the generated pty.toml command line', async () => {
    const r = await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'alice',
        permissionMode: 'bypassPermissions',
      }),
      ctx
    );
    // pty.toml quotes the shell line; we don't reconstruct it here,
    // just assert the resolved mode appears in the emitted preview.
    expect(r.ptyTomlPreview).toContain('--permission-mode bypassPermissions');
    expect(r.ptyTomlPreview).not.toContain('--permission-mode auto');
  });

  it('codex launches accept the flag silently (surface has no effect)', async () => {
    // The mode resolves in `LaunchResult` regardless of harness so the
    // dry-run summary is consistent, but the codex argv is untouched.
    const r = await cmdLaunch(
      baseInput({
        harness: 'codex',
        identity: 'alice',
        permissionMode: 'bypassPermissions',
      }),
      ctx
    );
    expect(r.permissionMode).toBe('bypassPermissions');
    expect(r.argv).not.toContain('--permission-mode');
  });

  it('CLI wrapper: --permission-mode flag appears in the dry-run summary', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(
      [
        'claude',
        '--identity',
        'alice',
        '--permission-mode',
        'bypassPermissions',
        '--dry-run',
      ],
      ctx
    );
    expect(rc).toBe(0);
    expect(stdoutBuf).toContain('permission-mode: bypassPermissions');
    // And still shows up in the harness argv line.
    expect(stdoutBuf).toContain('--permission-mode bypassPermissions');
  });

  it('CLI wrapper: default summary shows permission-mode: auto', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(['claude', '--identity', 'alice', '--dry-run'], ctx);
    expect(stdoutBuf).toContain('permission-mode: auto');
  });
});

// ─── pty.toml content ─────────────────────────────────────────────────

describe('cmdLaunch — pty.toml generation', () => {
  it('emits a pty.toml preview even when pty is not on PATH', async () => {
    const r = await cmdLaunch(baseInput({ identity: 'alice' }), ctx);
    expect(r.ptyTomlPreview).not.toBeNull();
    expect(r.ptyTomlPreview).toContain('prefix = "repo"');
    expect(r.ptyTomlPreview).toContain('[sessions.claude]');
    expect(r.ptyTomlPreview).toContain('ST_AGENT = "alice"');
  });

  it('claude preview has no ding sidecar', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.ptyTomlPreview).not.toContain('[sessions.ding]');
  });

  it('codex preview includes the coord ding sidecar', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', identity: 'alice' }),
      ctx
    );
    expect(r.ptyTomlPreview).toContain('[sessions.ding]');
    expect(r.ptyTomlPreview).toContain(
      'coord ding codex --identity alice'
    );
    expect(r.ptyTomlPreview).toContain('strategy = "permanent"');
  });

  it('--session-name overrides the pty session key', async () => {
    const r = await cmdLaunch(
      baseInput({ harness: 'codex', identity: 'alice', sessionName: 'agentx' }),
      ctx
    );
    expect(r.ptyTomlPreview).toContain('[sessions.agentx]');
    expect(r.ptyTomlPreview).toContain(
      'coord ding agentx --identity alice'
    );
  });
});

// ─── pty detection + write behavior ────────────────────────────────────

describe('cmdLaunch — pty detection', () => {
  it('reports pty unavailable when detection returns empty', async () => {
    const r = await cmdLaunch(baseInput({ ptyBinPath: '' }), ctx);
    expect(r.usedPty).toBe(false);
    expect(r.ptyTomlPath).toBeNull();
  });

  it('reports pty available when ptyBinPath is a real file', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    const r = await cmdLaunch(baseInput({ ptyBinPath: fakePty }), ctx);
    expect(r.usedPty).toBe(true);
    expect(r.ptyTomlPath).toBe(join(cwd, 'pty.toml'));
  });

  it('--no-pty forces off even when pty is available', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    const r = await cmdLaunch(
      baseInput({ ptyBinPath: fakePty, noPty: true }),
      ctx
    );
    expect(r.usedPty).toBe(false);
  });
});

// ─── .claude-session-id handling ───────────────────────────────────────

describe('cmdLaunch — claude session id', () => {
  it('reads an existing .claude-session-id and preserves it', async () => {
    writeFileSync(
      join(cwd, '.claude-session-id'),
      'preserved-uuid-1234\n'
    );
    const r = await cmdLaunch(
      baseInput({ harness: 'claude', identity: 'alice' }),
      ctx
    );
    expect(r.argv).toContain('preserved-uuid-1234');
    expect(r.claudeSessionIdPath).toBe(join(cwd, '.claude-session-id'));
    // dry-run didn't overwrite.
    expect(readFileSync(join(cwd, '.claude-session-id'), 'utf8')).toBe(
      'preserved-uuid-1234\n'
    );
  });

  it('codex path has no .claude-session-id reference', async () => {
    const r = await cmdLaunch(baseInput({ harness: 'codex' }), ctx);
    expect(r.claudeSessionIdPath).toBeNull();
  });
});

// ─── Dry-run stdout summary ────────────────────────────────────────────

describe('cmdLaunchCli — dry-run summary', () => {
  it('the CLI wrapper prints the summary block on --dry-run', async () => {
    // Route through the CLI wrapper for the assertions on stdout.
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(
      ['claude', '--identity', 'alice', '--dry-run'],
      ctx
    );
    expect(rc).toBe(0);
    expect(stdoutBuf).toContain('identity:       alice');
    expect(stdoutBuf).toContain('channel mode:   on');
    expect(stdoutBuf).toContain('harness argv:');
    expect(stdoutBuf).toContain('pty.toml');
  });

  it('the CLI wrapper reports an anon fallback line in the summary', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await cmdLaunchCli(['codex', '--dry-run'], ctx);
    expect(stdoutBuf).toMatch(/identity:.+anon-[0-9a-z]{6}/);
    expect(stdoutBuf).toContain('throwaway; set ST_AGENT to persist');
  });

  it('errors on an unsupported harness', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await expect(
      cmdLaunchCli(['pi'], ctx)
    ).rejects.toThrow(/unknown harness/);
  });

  it('errors on an unknown flag', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    await expect(
      cmdLaunchCli(['claude', '--bogus'], ctx)
    ).rejects.toThrow(/unknown flag/);
  });

  it('missing harness arg → help + exit 2', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli([], ctx);
    expect(rc).toBe(2);
    expect(stderrBuf).toContain('usage: st launch');
  });

  it('--help returns 0 and prints the help block', async () => {
    const { cmdLaunchCli } = await import('../../src/commands/launch.ts');
    const rc = await cmdLaunchCli(['--help'], ctx);
    expect(rc).toBe(0);
    expect(stderrBuf).toContain('usage: st launch');
    expect(stderrBuf).toContain('--model');
    expect(stderrBuf).toContain('anon-<rand6>');
  });
});

// ─── Ensures inbox/archive created for the resolved identity ───────────

describe('cmdLaunch — side effects (non-dry-run)', () => {
  it('lazy-creates the agent inbox+archive when not dry-run', async () => {
    // Non-dry-run path; ptyBinPath='' so no pty spawn happens, and
    // captureOnly true to skip the actual harness spawn.
    await cmdLaunch(
      baseInput({
        identity: 'carol',
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(existsSync(join(coordRoot, 'carol', 'inbox'))).toBe(true);
    expect(existsSync(join(coordRoot, 'carol', 'archive'))).toBe(true);
  });

  it('writes pty.toml (skip-if-exists) when pty is available', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    await cmdLaunch(
      baseInput({
        identity: 'dave',
        ptyBinPath: fakePty,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const path = join(cwd, 'pty.toml');
    expect(existsSync(path)).toBe(true);
    const content = readFileSync(path, 'utf8');
    expect(content).toContain('ST_AGENT = "dave"');

    // Second run does NOT overwrite (skip-if-exists).
    writeFileSync(path, '# user hand-edited\n');
    await cmdLaunch(
      baseInput({
        identity: 'eve',
        ptyBinPath: fakePty,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    expect(readFileSync(path, 'utf8')).toBe('# user hand-edited\n');
  });

  it('writes a fresh .claude-session-id when none exists (claude path)', async () => {
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'frank',
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const path = join(cwd, '.claude-session-id');
    expect(existsSync(path)).toBe(true);
    // UUID shape: 8-4-4-4-12 hex.
    const content = readFileSync(path, 'utf8').trim();
    expect(content).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
    );
  });
});

// ─── Live-path regression (brief-016 followup: require-not-defined) ────
//
// These tests exercise the code paths that a `--dry-run` skips —
// specifically the newUuid()/randomUUID call site that crashed under
// CJS `require('node:crypto')` when smalltalk ran as ESM. A `require`
// regression here fails the test rather than the live user run.

describe('cmdLaunch — live-path regression (dry-run bypasses this)', () => {
  it('claude live path: .claude-session-id + mcp.json + pty.toml all land on disk without runtime errors', async () => {
    // captureOnly: true skips only the harness spawn; every earlier
    // side-effect (session-id gen via randomUUID, cmdInit write,
    // pty.toml write, ensureIdentityDirs) runs for real.
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    let threw: unknown = null;
    try {
      await cmdLaunch(
        baseInput({
          harness: 'claude',
          identity: 'live-alice',
          dryRun: false,
          captureOnly: true,
          ptyBinPath: fakePty,
        }),
        ctx
      );
    } catch (err) {
      threw = err;
    }
    expect(threw).toBeNull();
    // The three files that must exist post-live-run:
    expect(existsSync(join(cwd, '.claude-session-id'))).toBe(true);
    expect(existsSync(join(cwd, '.mcp.json'))).toBe(true);
    expect(existsSync(join(cwd, 'pty.toml'))).toBe(true);
    // And the UUID must be well-formed — proves randomUUID() was
    // actually reachable at runtime (a `require`-not-defined regression
    // throws before this write happens).
    const sid = readFileSync(
      join(cwd, '.claude-session-id'),
      'utf8'
    ).trim();
    expect(sid).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
    );
  });

  it('codex live path: mcp.json + pty.toml with ding sidecar land without runtime errors', async () => {
    const fakePty = join(scratch, 'fake-pty');
    writeFileSync(fakePty, '#!/bin/sh\necho ok\n');
    let threw: unknown = null;
    try {
      await cmdLaunch(
        baseInput({
          harness: 'codex',
          identity: 'live-bob',
          dryRun: false,
          captureOnly: true,
          ptyBinPath: fakePty,
        }),
        ctx
      );
    } catch (err) {
      threw = err;
    }
    expect(threw).toBeNull();
    expect(existsSync(join(cwd, '.mcp.json'))).toBe(true);
    const pty = readFileSync(join(cwd, 'pty.toml'), 'utf8');
    expect(pty).toContain('[sessions.codex]');
    expect(pty).toContain('[sessions.ding]');
    expect(pty).toContain('coord ding codex --identity live-bob');
    // Codex path doesn't touch newUuid(), but the init.ts /
    // status.ts sibling `require`s in the error paths are compiled
    // in this run — a regression there would still surface.
  });

  it('two live launches in a row generate distinct UUIDs (proves randomUUID is not memoized)', async () => {
    const cwd2 = join(scratch, 'repo2');
    mkdirSync(cwd2, { recursive: true });
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'live-carol',
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    await cmdLaunch(
      baseInput({
        harness: 'claude',
        identity: 'live-dave',
        cwd: cwd2,
        dryRun: false,
        captureOnly: true,
      }),
      ctx
    );
    const sid1 = readFileSync(
      join(cwd, '.claude-session-id'),
      'utf8'
    ).trim();
    const sid2 = readFileSync(
      join(cwd2, '.claude-session-id'),
      'utf8'
    ).trim();
    expect(sid1).not.toBe(sid2);
  });
});
